services:
  docs:
    image: conversa_dj_local_docs
    container_name: conversa_dj_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./conversa_dj:/app/conversa_dj:z
    ports:
      - '9000:9000'
    command: /start-docs
